blank_issues_enabled: true
contact_links:
  - name: SD Maid Wiki
    url: https://github.com/d4rken-org/sdmaid-se/wiki/Bugs
    about: Read this before opening a bug report.
  - name: FAQ
    url: https://github.com/d4rken-org/sdmaid-se/wiki/FAQ
    about: Check if your question is already answered here.
