package eu.darken.sdmse.common.theming

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Cinnabar: deep crimson primary + warm gold/ochre tertiary, inspired by lacquer ware.
object SdmSeColorsCinnabar {

    val LightDefault = lightColorScheme(
        primary = Color(0xFFA93226),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFCCBC),
        onPrimaryContainer = Color(0xFF410001),
        inversePrimary = Color(0xFFFF8978),
        secondary = Color(0xFF6E4843),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDAD3),
        onSecondaryContainer = Color(0xFF260F0B),
        tertiary = Color(0xFFB8860B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFE7B0),
        onTertiaryContainer = Color(0xFF2A1A00),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF1F1411),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF1F1411),
        surfaceVariant = Color(0xFFF4DDD8),
        onSurfaceVariant = Color(0xFF534340),
        surfaceTint = Color(0xFFA93226),
        inverseSurface = Color(0xFF362F2D),
        inverseOnSurface = Color(0xFFFBEEEB),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF85736F),
        outlineVariant = Color(0xFFD7C2BD),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFE7D6D2),
        surfaceBright = Color(0xFFFFF8F6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFCEEEA),
        surfaceContainer = Color(0xFFF6E7E2),
        surfaceContainerHigh = Color(0xFFEFDFDA),
        surfaceContainerHighest = Color(0xFFE9D8D3),
    )

    val DarkDefault = darkColorScheme(
        primary = Color(0xFFFF8978),
        onPrimary = Color(0xFF5C0F0A),
        primaryContainer = Color(0xFF7E1D14),
        onPrimaryContainer = Color(0xFFFFD9D2),
        inversePrimary = Color(0xFFA93226),
        secondary = Color(0xFFE3BCB4),
        onSecondary = Color(0xFF3D2520),
        secondaryContainer = Color(0xFF583B37),
        onSecondaryContainer = Color(0xFFFFDAD3),
        tertiary = Color(0xFFFFD580),
        onTertiary = Color(0xFF3F2A00),
        tertiaryContainer = Color(0xFF5A4100),
        onTertiaryContainer = Color(0xFFFFE7B0),
        background = Color(0xFF211412),
        onBackground = Color(0xFFEEDFDB),
        surface = Color(0xFF211412),
        onSurface = Color(0xFFEEDFDB),
        surfaceVariant = Color(0xFF534340),
        onSurfaceVariant = Color(0xFFD7C2BD),
        surfaceTint = Color(0xFFFF8978),
        inverseSurface = Color(0xFFEEDFDB),
        inverseOnSurface = Color(0xFF362F2D),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFFA08C88),
        outlineVariant = Color(0xFF534340),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF211412),
        surfaceBright = Color(0xFF483B38),
        surfaceContainerLowest = Color(0xFF1B0F0D),
        surfaceContainerLow = Color(0xFF2A1D1A),
        surfaceContainer = Color(0xFF2E211E),
        surfaceContainerHigh = Color(0xFF392B28),
        surfaceContainerHighest = Color(0xFF443532),
    )

    val LightMediumContrast = lightColorScheme(
        primary = Color(0xFF7E1D14),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF9D2B1D),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFFF8978),
        secondary = Color(0xFF4F2E2A),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF815751),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF7A5808),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF8E6B12),
        onTertiaryContainer = Color(0xFFFFFFFF),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF1F1411),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF160B09),
        surfaceVariant = Color(0xFFF4DDD8),
        onSurfaceVariant = Color(0xFF42332F),
        surfaceTint = Color(0xFF7E1D14),
        inverseSurface = Color(0xFF362F2D),
        inverseOnSurface = Color(0xFFFBEEEB),
        error = Color(0xFF740006),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFCF2C27),
        onErrorContainer = Color(0xFFFFFFFF),
        outline = Color(0xFF5F4E4B),
        outlineVariant = Color(0xFF7B6864),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFE7D6D2),
        surfaceBright = Color(0xFFFFF8F6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFCEEEA),
        surfaceContainer = Color(0xFFF6E7E2),
        surfaceContainerHigh = Color(0xFFEFDFDA),
        surfaceContainerHighest = Color(0xFFE9D8D3),
    )

    val DarkMediumContrast = darkColorScheme(
        primary = Color(0xFFFFB1A4),
        onPrimary = Color(0xFF3A0500),
        primaryContainer = Color(0xFFCA5547),
        onPrimaryContainer = Color(0xFF000000),
        inversePrimary = Color(0xFF6E1109),
        secondary = Color(0xFFFAD2CB),
        onSecondary = Color(0xFF311B17),
        secondaryContainer = Color(0xFFA98780),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFFFFE198),
        onTertiary = Color(0xFF301F00),
        tertiaryContainer = Color(0xFFC79722),
        onTertiaryContainer = Color(0xFF000000),
        background = Color(0xFF211412),
        onBackground = Color(0xFFEEDFDB),
        surface = Color(0xFF211412),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF534340),
        onSurfaceVariant = Color(0xFFEDD7D1),
        surfaceTint = Color(0xFFFFB1A4),
        inverseSurface = Color(0xFFEEDFDB),
        inverseOnSurface = Color(0xFF2C2522),
        error = Color(0xFFFFD2CC),
        onError = Color(0xFF540003),
        errorContainer = Color(0xFFFF5449),
        onErrorContainer = Color(0xFF000000),
        outline = Color(0xFFC4AFAB),
        outlineVariant = Color(0xFFA08C88),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF211412),
        surfaceBright = Color(0xFF483B38),
        surfaceContainerLowest = Color(0xFF1B0F0D),
        surfaceContainerLow = Color(0xFF2A1D1A),
        surfaceContainer = Color(0xFF2E211E),
        surfaceContainerHigh = Color(0xFF392B28),
        surfaceContainerHighest = Color(0xFF443532),
    )

    val LightHighContrast = lightColorScheme(
        primary = Color(0xFF53000A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF7E1D14),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFFFE7E3),
        secondary = Color(0xFF301710),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF4F2E2A),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF4A3300),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF7A5808),
        onTertiaryContainer = Color(0xFFFFFFFF),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF1F1411),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF000000),
        surfaceVariant = Color(0xFFF4DDD8),
        onSurfaceVariant = Color(0xFF000000),
        outline = Color(0xFF2B201E),
        outlineVariant = Color(0xFF4A3A37),
        surfaceTint = Color(0xFF53000A),
        inverseSurface = Color(0xFF362F2D),
        inverseOnSurface = Color(0xFFFFFFFF),
        error = Color(0xFF600004),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF98000A),
        onErrorContainer = Color(0xFFFFFFFF),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFE7D6D2),
        surfaceBright = Color(0xFFFFF8F6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFCEEEA),
        surfaceContainer = Color(0xFFF6E7E2),
        surfaceContainerHigh = Color(0xFFEFDFDA),
        surfaceContainerHighest = Color(0xFFE9D8D3),
    )

    val DarkHighContrast = darkColorScheme(
        primary = Color(0xFFFFEAE7),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0xFFFFB1A4),
        onPrimaryContainer = Color(0xFF110000),
        inversePrimary = Color(0xFF4D0008),
        secondary = Color(0xFFFFEDE9),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xFFC4A097),
        onSecondaryContainer = Color(0xFF0B0301),
        tertiary = Color(0xFFFFF1D1),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFFE0B044),
        onTertiaryContainer = Color(0xFF110800),
        background = Color(0xFF211412),
        onBackground = Color(0xFFEEDFDB),
        surface = Color(0xFF211412),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF534340),
        onSurfaceVariant = Color(0xFFFFFFFF),
        outline = Color(0xFFF5DDD7),
        outlineVariant = Color(0xFFC4AFAB),
        surfaceTint = Color(0xFFFFEAE7),
        inverseSurface = Color(0xFFEEDFDB),
        inverseOnSurface = Color(0xFF000000),
        error = Color(0xFFFFECE9),
        onError = Color(0xFF000000),
        errorContainer = Color(0xFFFFAEA4),
        onErrorContainer = Color(0xFF220001),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF211412),
        surfaceBright = Color(0xFF483B38),
        surfaceContainerLowest = Color(0xFF1B0F0D),
        surfaceContainerLow = Color(0xFF2A1D1A),
        surfaceContainer = Color(0xFF2E211E),
        surfaceContainerHigh = Color(0xFF392B28),
        surfaceContainerHighest = Color(0xFF443532),
    )

    fun lightScheme(style: ThemeStyle): ColorScheme = when (style) {
        ThemeStyle.MEDIUM_CONTRAST -> LightMediumContrast
        ThemeStyle.HIGH_CONTRAST -> LightHighContrast
        else -> LightDefault
    }

    fun darkScheme(style: ThemeStyle): ColorScheme = when (style) {
        ThemeStyle.MEDIUM_CONTRAST -> DarkMediumContrast
        ThemeStyle.HIGH_CONTRAST -> DarkHighContrast
        else -> DarkDefault
    }
}
