package eu.darken.sdmse.common.theming

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object SdmSeColorsScholar {

    val LightDefault = lightColorScheme(
        primary = Color(0xFF6B4F2A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE8D5B0),
        onPrimaryContainer = Color(0xFF2A1F0E),
        secondary = Color(0xFF786A52),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE3DAC4),
        onSecondaryContainer = Color(0xFF2A2418),
        tertiary = Color(0xFF8B5A2B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF5DEAA),
        onTertiaryContainer = Color(0xFF2E1C09),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFF8F1E4),
        onBackground = Color(0xFF2E2517),
        surface = Color(0xFFF8F1E4),
        onSurface = Color(0xFF2E2517),
        surfaceVariant = Color(0xFFEBE0CD),
        onSurfaceVariant = Color(0xFF4A4030),
        outline = Color(0xFF7C715B),
        outlineVariant = Color(0xFFCABD9F),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF322A1E),
        inverseOnSurface = Color(0xFFF0E7D2),
        inversePrimary = Color(0xFFD7B988),
        surfaceDim = Color(0xFFDBD3BF),
        surfaceBright = Color(0xFFF8F1E4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF3EAD4),
        surfaceContainer = Color(0xFFEDE3C8),
        surfaceContainerHigh = Color(0xFFE6DCBE),
        surfaceContainerHighest = Color(0xFFDFD4B2),
    )

    val DarkDefault = darkColorScheme(
        primary = Color(0xFFD7B988),
        onPrimary = Color(0xFF3D2A0F),
        primaryContainer = Color(0xFF54401F),
        onPrimaryContainer = Color(0xFFF5E3C2),
        secondary = Color(0xFFC7B89C),
        onSecondary = Color(0xFF322920),
        secondaryContainer = Color(0xFF4B4234),
        onSecondaryContainer = Color(0xFFE3DAC4),
        tertiary = Color(0xFFE6BE7E),
        onTertiary = Color(0xFF3F2A0A),
        tertiaryContainer = Color(0xFF5D4316),
        onTertiaryContainer = Color(0xFFFCDFAC),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF1C1612),
        onBackground = Color(0xFFEBE0CD),
        surface = Color(0xFF1C1612),
        onSurface = Color(0xFFEBE0CD),
        surfaceVariant = Color(0xFF4A4030),
        onSurfaceVariant = Color(0xFFCABD9F),
        outline = Color(0xFF948871),
        outlineVariant = Color(0xFF4A4030),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEBE0CD),
        inverseOnSurface = Color(0xFF322A1E),
        inversePrimary = Color(0xFF6B4F2A),
        surfaceDim = Color(0xFF1C1612),
        surfaceBright = Color(0xFF423A2D),
        surfaceContainerLowest = Color(0xFF150F0B),
        surfaceContainerLow = Color(0xFF241D17),
        surfaceContainer = Color(0xFF28211B),
        surfaceContainerHigh = Color(0xFF332B23),
        surfaceContainerHighest = Color(0xFF3E362C),
    )

    val LightMediumContrast = lightColorScheme(
        primary = Color(0xFF4E371A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF6F5732),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF5A4D37),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF6F6147),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF683E12),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF84592E),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF740006),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFCF2C27),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFF8F1E4),
        onBackground = Color(0xFF2E2517),
        surface = Color(0xFFF8F1E4),
        onSurface = Color(0xFF221B0F),
        surfaceVariant = Color(0xFFEBE0CD),
        onSurfaceVariant = Color(0xFF3A311E),
        outline = Color(0xFF564B36),
        outlineVariant = Color(0xFF716552),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF322A1E),
        inverseOnSurface = Color(0xFFF0E7D2),
        inversePrimary = Color(0xFFD7B988),
        surfaceDim = Color(0xFFDBD3BF),
        surfaceBright = Color(0xFFF8F1E4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF3EAD4),
        surfaceContainer = Color(0xFFEDE3C8),
        surfaceContainerHigh = Color(0xFFE6DCBE),
        surfaceContainerHighest = Color(0xFFDFD4B2),
    )

    val DarkMediumContrast = darkColorScheme(
        primary = Color(0xFFEFD0A0),
        onPrimary = Color(0xFF2D1F08),
        primaryContainer = Color(0xFF9E8454),
        onPrimaryContainer = Color(0xFF000000),
        secondary = Color(0xFFDDCEB0),
        onSecondary = Color(0xFF271E15),
        secondaryContainer = Color(0xFF918367),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFFFFD498),
        onTertiary = Color(0xFF2C1D05),
        tertiaryContainer = Color(0xFFAD8956),
        onTertiaryContainer = Color(0xFF000000),
        error = Color(0xFFFFD2CC),
        onError = Color(0xFF540003),
        errorContainer = Color(0xFFFF5449),
        onErrorContainer = Color(0xFF000000),
        background = Color(0xFF1C1612),
        onBackground = Color(0xFFEBE0CD),
        surface = Color(0xFF1C1612),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF4A4030),
        onSurfaceVariant = Color(0xFFDFD3BD),
        outline = Color(0xFFB5A893),
        outlineVariant = Color(0xFF948871),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEBE0CD),
        inverseOnSurface = Color(0xFF262017),
        inversePrimary = Color(0xFF503A1A),
        surfaceDim = Color(0xFF1C1612),
        surfaceBright = Color(0xFF423A2D),
        surfaceContainerLowest = Color(0xFF150F0B),
        surfaceContainerLow = Color(0xFF241D17),
        surfaceContainer = Color(0xFF28211B),
        surfaceContainerHigh = Color(0xFF332B23),
        surfaceContainerHighest = Color(0xFF3E362C),
    )

    val LightHighContrast = lightColorScheme(
        primary = Color(0xFF2F2008),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF553B1C),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF2F2719),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF4F4332),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF3C2103),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF5E371A),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF600004),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF98000A),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFF8F1E4),
        onBackground = Color(0xFF2E2517),
        surface = Color(0xFFF8F1E4),
        onSurface = Color(0xFF000000),
        surfaceVariant = Color(0xFFEBE0CD),
        onSurfaceVariant = Color(0xFF000000),
        outline = Color(0xFF2A2316),
        outlineVariant = Color(0xFF4A4030),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF322A1E),
        inverseOnSurface = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFD7B988),
        surfaceDim = Color(0xFFDBD3BF),
        surfaceBright = Color(0xFFF8F1E4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF3EAD4),
        surfaceContainer = Color(0xFFEDE3C8),
        surfaceContainerHigh = Color(0xFFE6DCBE),
        surfaceContainerHighest = Color(0xFFDFD4B2),
    )

    val DarkHighContrast = darkColorScheme(
        primary = Color(0xFFFFEBC8),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0xFFD3B385),
        onPrimaryContainer = Color(0xFF0F0700),
        secondary = Color(0xFFF5E5C5),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xFFC3B499),
        onSecondaryContainer = Color(0xFF0E0904),
        tertiary = Color(0xFFFFEBC8),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFFE2B57A),
        onTertiaryContainer = Color(0xFF110600),
        error = Color(0xFFFFECE9),
        onError = Color(0xFF000000),
        errorContainer = Color(0xFFFFAEA4),
        onErrorContainer = Color(0xFF220001),
        background = Color(0xFF1C1612),
        onBackground = Color(0xFFEBE0CD),
        surface = Color(0xFF1C1612),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF4A4030),
        onSurfaceVariant = Color(0xFFFFFFFF),
        outline = Color(0xFFF1E5CF),
        outlineVariant = Color(0xFFC3B89E),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEBE0CD),
        inverseOnSurface = Color(0xFF000000),
        inversePrimary = Color(0xFF503A1A),
        surfaceDim = Color(0xFF1C1612),
        surfaceBright = Color(0xFF423A2D),
        surfaceContainerLowest = Color(0xFF150F0B),
        surfaceContainerLow = Color(0xFF241D17),
        surfaceContainer = Color(0xFF28211B),
        surfaceContainerHigh = Color(0xFF332B23),
        surfaceContainerHighest = Color(0xFF3E362C),
    )

    fun lightScheme(style: ThemeStyle): ColorScheme = when (style) {
        ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> LightDefault
        ThemeStyle.MEDIUM_CONTRAST -> LightMediumContrast
        ThemeStyle.HIGH_CONTRAST -> LightHighContrast
    }

    fun darkScheme(style: ThemeStyle): ColorScheme = when (style) {
        ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> DarkDefault
        ThemeStyle.MEDIUM_CONTRAST -> DarkMediumContrast
        ThemeStyle.HIGH_CONTRAST -> DarkHighContrast
    }
}
