package eu.darken.sdmse.common.theming

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Cobalt: deep blue primary + warm orange tertiary, ported from Butler's Blue palette.
object SdmSeColorsCobalt {

    val LightDefault = lightColorScheme(
        primary = Color(0xFF1565C0),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD4E3FF),
        onPrimaryContainer = Color(0xFF001C38),
        inversePrimary = Color(0xFFA6C8FF),
        secondary = Color(0xFF565E71),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFDAE2F9),
        onSecondaryContainer = Color(0xFF131C2B),
        tertiary = Color(0xFFFF6D00),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDBCA),
        onTertiaryContainer = Color(0xFF311300),
        background = Color(0xFFF8F9FF),
        onBackground = Color(0xFF191C20),
        surface = Color(0xFFF8F9FF),
        onSurface = Color(0xFF191C20),
        surfaceVariant = Color(0xFFE0E2EC),
        onSurfaceVariant = Color(0xFF44474E),
        surfaceTint = Color(0xFF1565C0),
        inverseSurface = Color(0xFF2E3135),
        inverseOnSurface = Color(0xFFF0F1F6),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF74777F),
        outlineVariant = Color(0xFFC4C6D0),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFD8D9E0),
        surfaceBright = Color(0xFFF8F9FF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F3FA),
        surfaceContainer = Color(0xFFECEEF4),
        surfaceContainerHigh = Color(0xFFE6E8EF),
        surfaceContainerHighest = Color(0xFFE0E2E9),
    )

    val DarkDefault = darkColorScheme(
        primary = Color(0xFFA6C8FF),
        onPrimary = Color(0xFF00315C),
        primaryContainer = Color(0xFF004A86),
        onPrimaryContainer = Color(0xFFD4E3FF),
        inversePrimary = Color(0xFF1565C0),
        secondary = Color(0xFFBEC6DC),
        onSecondary = Color(0xFF283041),
        secondaryContainer = Color(0xFF3F4758),
        onSecondaryContainer = Color(0xFFDAE2F9),
        tertiary = Color(0xFFFFB68A),
        onTertiary = Color(0xFF502400),
        tertiaryContainer = Color(0xFF723500),
        onTertiaryContainer = Color(0xFFFFDBCA),
        background = Color(0xFF111418),
        onBackground = Color(0xFFE1E2E8),
        surface = Color(0xFF111418),
        onSurface = Color(0xFFE1E2E8),
        surfaceVariant = Color(0xFF44474E),
        onSurfaceVariant = Color(0xFFC4C6D0),
        surfaceTint = Color(0xFFA6C8FF),
        inverseSurface = Color(0xFFE1E2E8),
        inverseOnSurface = Color(0xFF2E3135),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8E9099),
        outlineVariant = Color(0xFF44474E),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF111418),
        surfaceBright = Color(0xFF36393E),
        surfaceContainerLowest = Color(0xFF0B0E12),
        surfaceContainerLow = Color(0xFF191C20),
        surfaceContainer = Color(0xFF1D2025),
        surfaceContainerHigh = Color(0xFF272B2F),
        surfaceContainerHighest = Color(0xFF32353A),
    )

    val LightMediumContrast = lightColorScheme(
        primary = Color(0xFF00468B),
        onPrimary = Color(0xFFFFFFFF),
        // Darkened from Butler's #3F7CD8 so white text passes WCAG AA.
        primaryContainer = Color(0xFF22579D),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFA6C8FF),
        secondary = Color(0xFF3A4253),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF6C7487),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFFB34900),
        onTertiary = Color(0xFFFFFFFF),
        // Darkened from Butler's #FF8D42 so white text passes WCAG AA.
        tertiaryContainer = Color(0xFFA14000),
        onTertiaryContainer = Color(0xFFFFFFFF),
        background = Color(0xFFF8F9FF),
        onBackground = Color(0xFF191C20),
        surface = Color(0xFFF8F9FF),
        onSurface = Color(0xFF191C20),
        surfaceVariant = Color(0xFFE0E2EC),
        onSurfaceVariant = Color(0xFF40434A),
        surfaceTint = Color(0xFF00468B),
        inverseSurface = Color(0xFF2E3135),
        inverseOnSurface = Color(0xFFF0F1F6),
        error = Color(0xFF8C0009),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFDA342E),
        onErrorContainer = Color(0xFFFFFFFF),
        outline = Color(0xFF5C5F67),
        outlineVariant = Color(0xFF787B83),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFD8D9E0),
        surfaceBright = Color(0xFFF8F9FF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F3FA),
        surfaceContainer = Color(0xFFECEEF4),
        surfaceContainerHigh = Color(0xFFE6E8EF),
        surfaceContainerHighest = Color(0xFFE0E2E9),
    )

    val DarkMediumContrast = darkColorScheme(
        primary = Color(0xFFABCCFF),
        onPrimary = Color(0xFF00172F),
        primaryContainer = Color(0xFF6091D0),
        onPrimaryContainer = Color(0xFF000000),
        inversePrimary = Color(0xFF004B87),
        secondary = Color(0xFFC2CAE0),
        onSecondary = Color(0xFF0E1626),
        secondaryContainer = Color(0xFF8890A5),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFFFFBB91),
        onTertiary = Color(0xFF2A1000),
        tertiaryContainer = Color(0xFFC97E3F),
        onTertiaryContainer = Color(0xFF000000),
        background = Color(0xFF111418),
        onBackground = Color(0xFFE1E2E8),
        surface = Color(0xFF111418),
        onSurface = Color(0xFFFAFAFF),
        surfaceVariant = Color(0xFF44474E),
        onSurfaceVariant = Color(0xFFC8CAD4),
        surfaceTint = Color(0xFFABCCFF),
        inverseSurface = Color(0xFFE1E2E8),
        inverseOnSurface = Color(0xFF282A2F),
        error = Color(0xFFFFBAB1),
        onError = Color(0xFF370001),
        errorContainer = Color(0xFFFF5449),
        onErrorContainer = Color(0xFF000000),
        outline = Color(0xFFA0A3AC),
        outlineVariant = Color(0xFF80838C),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF111418),
        surfaceBright = Color(0xFF36393E),
        surfaceContainerLowest = Color(0xFF0B0E12),
        surfaceContainerLow = Color(0xFF191C20),
        surfaceContainer = Color(0xFF1D2025),
        surfaceContainerHigh = Color(0xFF272B2F),
        surfaceContainerHighest = Color(0xFF32353A),
    )

    val LightHighContrast = lightColorScheme(
        primary = Color(0xFF002346),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF00468B),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFDFECFF),
        secondary = Color(0xFF1A2231),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF3A4253),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF5C2400),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFB34900),
        onTertiaryContainer = Color(0xFFFFFFFF),
        background = Color(0xFFF8F9FF),
        onBackground = Color(0xFF191C20),
        surface = Color(0xFFF8F9FF),
        onSurface = Color(0xFF000000),
        surfaceVariant = Color(0xFFE0E2EC),
        onSurfaceVariant = Color(0xFF21242B),
        surfaceTint = Color(0xFF002346),
        inverseSurface = Color(0xFF2E3135),
        inverseOnSurface = Color(0xFFFFFFFF),
        error = Color(0xFF4E0002),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFF8C0009),
        onErrorContainer = Color(0xFFFFFFFF),
        outline = Color(0xFF40434A),
        outlineVariant = Color(0xFF40434A),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFD8D9E0),
        surfaceBright = Color(0xFFF8F9FF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F3FA),
        surfaceContainer = Color(0xFFECEEF4),
        surfaceContainerHigh = Color(0xFFE6E8EF),
        surfaceContainerHighest = Color(0xFFE0E2E9),
    )

    val DarkHighContrast = darkColorScheme(
        primary = Color(0xFFF9FAFF),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0xFFABCCFF),
        onPrimaryContainer = Color(0xFF000000),
        inversePrimary = Color(0xFF002B53),
        secondary = Color(0xFFF9FAFF),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xFFC2CAE0),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFFFFF9F7),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFFFFBB91),
        onTertiaryContainer = Color(0xFF000000),
        background = Color(0xFF111418),
        onBackground = Color(0xFFE1E2E8),
        surface = Color(0xFF111418),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF44474E),
        onSurfaceVariant = Color(0xFFF9FAFF),
        surfaceTint = Color(0xFFF9FAFF),
        inverseSurface = Color(0xFFE1E2E8),
        inverseOnSurface = Color(0xFF000000),
        error = Color(0xFFFFF9F9),
        onError = Color(0xFF000000),
        errorContainer = Color(0xFFFFBAB1),
        onErrorContainer = Color(0xFF000000),
        outline = Color(0xFFC8CAD4),
        outlineVariant = Color(0xFFC8CAD4),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF111418),
        surfaceBright = Color(0xFF36393E),
        surfaceContainerLowest = Color(0xFF0B0E12),
        surfaceContainerLow = Color(0xFF191C20),
        surfaceContainer = Color(0xFF1D2025),
        surfaceContainerHigh = Color(0xFF272B2F),
        surfaceContainerHighest = Color(0xFF32353A),
    )

    fun lightScheme(style: ThemeStyle): ColorScheme = when (style) {
        ThemeStyle.MEDIUM_CONTRAST -> LightMediumContrast
        ThemeStyle.HIGH_CONTRAST -> LightHighContrast
        else -> LightDefault
    }

    fun darkScheme(style: ThemeStyle): ColorScheme = when (style) {
        ThemeStyle.MEDIUM_CONTRAST -> DarkMediumContrast
        ThemeStyle.HIGH_CONTRAST -> DarkHighContrast
        else -> DarkDefault
    }
}
