name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: gradle/actions/wrapper-validation@06832c7b30a0129d7fb559bcc6e43d26f6374244 #v4.3.1
